export type AirportRegion = 'Africa' | 'Asia' | 'Middle East';

export interface AirportOption {
  city: string;
  airportName: string;
  country: string;
  iata: string;
  region: AirportRegion;
}

export const AIRPORT_PRESETS: AirportOption[] = [
  { city: 'Dubai', airportName: 'Dubai International Airport', country: 'United Arab Emirates', iata: 'DXB', region: 'Middle East' },
  { city: 'Dubai', airportName: 'Al Maktoum International Airport', country: 'United Arab Emirates', iata: 'DWC', region: 'Middle East' },
  { city: 'Abu Dhabi', airportName: 'Zayed International Airport', country: 'United Arab Emirates', iata: 'AUH', region: 'Middle East' },
  { city: 'Sharjah', airportName: 'Sharjah International Airport', country: 'United Arab Emirates', iata: 'SHJ', region: 'Middle East' },
  { city: 'Ras Al Khaimah', airportName: 'Ras Al Khaimah International Airport', country: 'United Arab Emirates', iata: 'RKT', region: 'Middle East' },
  { city: 'Al Ain', airportName: 'Al Ain International Airport', country: 'United Arab Emirates', iata: 'AAN', region: 'Middle East' },
  { city: 'Doha', airportName: 'Hamad International Airport', country: 'Qatar', iata: 'DOH', region: 'Middle East' },
  { city: 'Manama', airportName: 'Bahrain International Airport', country: 'Bahrain', iata: 'BAH', region: 'Middle East' },
  { city: 'Kuwait City', airportName: 'Kuwait International Airport', country: 'Kuwait', iata: 'KWI', region: 'Middle East' },
  { city: 'Muscat', airportName: 'Muscat International Airport', country: 'Oman', iata: 'MCT', region: 'Middle East' },
  { city: 'Salalah', airportName: 'Salalah Airport', country: 'Oman', iata: 'SLL', region: 'Middle East' },
  { city: 'Sohar', airportName: 'Sohar Airport', country: 'Oman', iata: 'OHS', region: 'Middle East' },
  { city: 'Khasab', airportName: 'Khasab Airport', country: 'Oman', iata: 'KHS', region: 'Middle East' },
  { city: 'Jeddah', airportName: 'King Abdulaziz International Airport', country: 'Saudi Arabia', iata: 'JED', region: 'Middle East' },
  { city: 'Riyadh', airportName: 'King Khalid International Airport', country: 'Saudi Arabia', iata: 'RUH', region: 'Middle East' },
  { city: 'Dammam', airportName: 'King Fahd International Airport', country: 'Saudi Arabia', iata: 'DMM', region: 'Middle East' },
  { city: 'Madinah', airportName: 'Prince Mohammad bin Abdulaziz International Airport', country: 'Saudi Arabia', iata: 'MED', region: 'Middle East' },
  { city: 'Abha', airportName: 'Abha International Airport', country: 'Saudi Arabia', iata: 'AHB', region: 'Middle East' },
  { city: 'Gassim', airportName: 'Prince Nayef bin Abdulaziz International Airport', country: 'Saudi Arabia', iata: 'ELQ', region: 'Middle East' },
  { city: 'Tabuk', airportName: 'Prince Sultan bin Abdulaziz Airport', country: 'Saudi Arabia', iata: 'TUU', region: 'Middle East' },
  { city: 'Taif', airportName: 'Taif International Airport', country: 'Saudi Arabia', iata: 'TIF', region: 'Middle East' },
  { city: 'Jazan', airportName: 'King Abdullah bin Abdulaziz Airport', country: 'Saudi Arabia', iata: 'GIZ', region: 'Middle East' },
  { city: 'Yanbu', airportName: 'Prince Abdul Mohsin bin Abdulaziz Airport', country: 'Saudi Arabia', iata: 'YNB', region: 'Middle East' },
  { city: 'Hofuf', airportName: 'Al-Ahsa International Airport', country: 'Saudi Arabia', iata: 'HOF', region: 'Middle East' },
  { city: 'Arar', airportName: 'Arar Domestic Airport', country: 'Saudi Arabia', iata: 'RAE', region: 'Middle East' },
  { city: 'Hail', airportName: 'Hail International Airport', country: 'Saudi Arabia', iata: 'HAS', region: 'Middle East' },
  { city: 'Najran', airportName: 'Najran Domestic Airport', country: 'Saudi Arabia', iata: 'EAM', region: 'Middle East' },
  { city: 'Al Jouf', airportName: 'Al Jouf Domestic Airport', country: 'Saudi Arabia', iata: 'AJF', region: 'Middle East' },
  { city: 'Amman', airportName: 'Queen Alia International Airport', country: 'Jordan', iata: 'AMM', region: 'Middle East' },
  { city: 'Aqaba', airportName: 'King Hussein International Airport', country: 'Jordan', iata: 'AQJ', region: 'Middle East' },
  { city: 'Beirut', airportName: 'Beirut-Rafic Hariri International Airport', country: 'Lebanon', iata: 'BEY', region: 'Middle East' },
  { city: 'Tel Aviv', airportName: 'Ben Gurion Airport', country: 'Israel', iata: 'TLV', region: 'Middle East' },
  { city: 'Haifa', airportName: 'Haifa Airport', country: 'Israel', iata: 'HFA', region: 'Middle East' },
  { city: 'Eilat', airportName: 'Ramon Airport', country: 'Israel', iata: 'ETM', region: 'Middle East' },
  { city: 'Tehran', airportName: 'Imam Khomeini International Airport', country: 'Iran', iata: 'IKA', region: 'Middle East' },
  { city: 'Tehran', airportName: 'Mehrabad International Airport', country: 'Iran', iata: 'THR', region: 'Middle East' },
  { city: 'Mashhad', airportName: 'Shahid Hasheminejad International Airport', country: 'Iran', iata: 'MHD', region: 'Middle East' },
  { city: 'Shiraz', airportName: 'Shiraz Shahid Dastghaib International Airport', country: 'Iran', iata: 'SYZ', region: 'Middle East' },
  { city: 'Isfahan', airportName: 'Isfahan International Airport', country: 'Iran', iata: 'IFN', region: 'Middle East' },
  { city: 'Tabriz', airportName: 'Tabriz International Airport', country: 'Iran', iata: 'TBZ', region: 'Middle East' },
  { city: 'Kish Island', airportName: 'Kish International Airport', country: 'Iran', iata: 'KIH', region: 'Middle East' },
  { city: 'Ahvaz', airportName: 'Ahvaz International Airport', country: 'Iran', iata: 'AWZ', region: 'Middle East' },
  { city: 'Bandar Abbas', airportName: 'Bandar Abbas International Airport', country: 'Iran', iata: 'BND', region: 'Middle East' },
  { city: 'Kerman', airportName: 'Kerman Airport', country: 'Iran', iata: 'KER', region: 'Middle East' },
  { city: 'Zahedan', airportName: 'Zahedan Airport', country: 'Iran', iata: 'ZAH', region: 'Middle East' },
  { city: 'Abadan', airportName: 'Abadan International Airport', country: 'Iran', iata: 'ABD', region: 'Middle East' },
  { city: 'Baghdad', airportName: 'Baghdad International Airport', country: 'Iraq', iata: 'BGW', region: 'Middle East' },
  { city: 'Basra', airportName: 'Basra International Airport', country: 'Iraq', iata: 'BSR', region: 'Middle East' },
  { city: 'Najaf', airportName: 'Al Najaf International Airport', country: 'Iraq', iata: 'NJF', region: 'Middle East' },
  { city: 'Erbil', airportName: 'Erbil International Airport', country: 'Iraq', iata: 'EBL', region: 'Middle East' },
  { city: 'Sulaymaniyah', airportName: 'Sulaymaniyah International Airport', country: 'Iraq', iata: 'ISU', region: 'Middle East' },
  { city: 'Damascus', airportName: 'Damascus International Airport', country: 'Syria', iata: 'DAM', region: 'Middle East' },
  { city: 'Aleppo', airportName: 'Aleppo International Airport', country: 'Syria', iata: 'ALP', region: 'Middle East' },
  { city: 'Sanaa', airportName: 'Sanaa International Airport', country: 'Yemen', iata: 'SAH', region: 'Middle East' },
  { city: 'Aden', airportName: 'Aden International Airport', country: 'Yemen', iata: 'ADE', region: 'Middle East' },
  { city: 'Riyan', airportName: 'Riyan Airport', country: 'Yemen', iata: 'RIY', region: 'Middle East' },

  { city: 'Dhaka', airportName: 'Hazrat Shahjalal International Airport', country: 'Bangladesh', iata: 'DAC', region: 'Asia' },
  { city: 'Chattogram', airportName: 'Shah Amanat International Airport', country: 'Bangladesh', iata: 'CGP', region: 'Asia' },
  { city: 'Sylhet', airportName: 'Osmani International Airport', country: 'Bangladesh', iata: 'ZYL', region: 'Asia' },
  { city: 'Coxs Bazar', airportName: 'Coxs Bazar Airport', country: 'Bangladesh', iata: 'CXB', region: 'Asia' },
  { city: 'Jashore', airportName: 'Jashore Airport', country: 'Bangladesh', iata: 'JSR', region: 'Asia' },
  { city: 'Rajshahi', airportName: 'Shah Makhdum Airport', country: 'Bangladesh', iata: 'RJH', region: 'Asia' },
  { city: 'Saidpur', airportName: 'Saidpur Airport', country: 'Bangladesh', iata: 'SPD', region: 'Asia' },
  { city: 'New Delhi', airportName: 'Indira Gandhi International Airport', country: 'India', iata: 'DEL', region: 'Asia' },
  { city: 'Mumbai', airportName: 'Chhatrapati Shivaji Maharaj International Airport', country: 'India', iata: 'BOM', region: 'Asia' },
  { city: 'Bengaluru', airportName: 'Kempegowda International Airport', country: 'India', iata: 'BLR', region: 'Asia' },
  { city: 'Chennai', airportName: 'Chennai International Airport', country: 'India', iata: 'MAA', region: 'Asia' },
  { city: 'Hyderabad', airportName: 'Rajiv Gandhi International Airport', country: 'India', iata: 'HYD', region: 'Asia' },
  { city: 'Kolkata', airportName: 'Netaji Subhas Chandra Bose International Airport', country: 'India', iata: 'CCU', region: 'Asia' },
  { city: 'Kochi', airportName: 'Cochin International Airport', country: 'India', iata: 'COK', region: 'Asia' },
  { city: 'Kozhikode', airportName: 'Calicut International Airport', country: 'India', iata: 'CCJ', region: 'Asia' },
  { city: 'Goa', airportName: 'Dabolim Airport', country: 'India', iata: 'GOI', region: 'Asia' },
  { city: 'Goa', airportName: 'Manohar International Airport', country: 'India', iata: 'GOX', region: 'Asia' },
  { city: 'Ahmedabad', airportName: 'Sardar Vallabhbhai Patel International Airport', country: 'India', iata: 'AMD', region: 'Asia' },
  { city: 'Pune', airportName: 'Pune Airport', country: 'India', iata: 'PNQ', region: 'Asia' },
  { city: 'Thiruvananthapuram', airportName: 'Thiruvananthapuram International Airport', country: 'India', iata: 'TRV', region: 'Asia' },
  { city: 'Lucknow', airportName: 'Chaudhary Charan Singh International Airport', country: 'India', iata: 'LKO', region: 'Asia' },
  { city: 'Jaipur', airportName: 'Jaipur International Airport', country: 'India', iata: 'JAI', region: 'Asia' },
  { city: 'Amritsar', airportName: 'Sri Guru Ram Dass Jee International Airport', country: 'India', iata: 'ATQ', region: 'Asia' },
  { city: 'Chandigarh', airportName: 'Chandigarh Airport', country: 'India', iata: 'IXC', region: 'Asia' },
  { city: 'Mangalore', airportName: 'Mangalore International Airport', country: 'India', iata: 'IXE', region: 'Asia' },
  { city: 'Madurai', airportName: 'Madurai Airport', country: 'India', iata: 'IXM', region: 'Asia' },
  { city: 'Bagdogra', airportName: 'Bagdogra Airport', country: 'India', iata: 'IXB', region: 'Asia' },
  { city: 'Guwahati', airportName: 'Lokpriya Gopinath Bordoloi International Airport', country: 'India', iata: 'GAU', region: 'Asia' },
  { city: 'Bhubaneswar', airportName: 'Biju Patnaik International Airport', country: 'India', iata: 'BBI', region: 'Asia' },
  { city: 'Nagpur', airportName: 'Dr. Babasaheb Ambedkar International Airport', country: 'India', iata: 'NAG', region: 'Asia' },
  { city: 'Patna', airportName: 'Jay Prakash Narayan Airport', country: 'India', iata: 'PAT', region: 'Asia' },
  { city: 'Indore', airportName: 'Devi Ahilya Bai Holkar Airport', country: 'India', iata: 'IDR', region: 'Asia' },
  { city: 'Coimbatore', airportName: 'Coimbatore International Airport', country: 'India', iata: 'CJB', region: 'Asia' },
  { city: 'Visakhapatnam', airportName: 'Visakhapatnam Airport', country: 'India', iata: 'VTZ', region: 'Asia' },
  { city: 'Varanasi', airportName: 'Lal Bahadur Shastri International Airport', country: 'India', iata: 'VNS', region: 'Asia' },
  { city: 'Ranchi', airportName: 'Birsa Munda Airport', country: 'India', iata: 'IXR', region: 'Asia' },
  { city: 'Udaipur', airportName: 'Maharana Pratap Airport', country: 'India', iata: 'UDR', region: 'Asia' },
  { city: 'Tiruchirappalli', airportName: 'Tiruchirappalli International Airport', country: 'India', iata: 'TRZ', region: 'Asia' },
  { city: 'Srinagar', airportName: 'Srinagar Airport', country: 'India', iata: 'SXR', region: 'Asia' },
  { city: 'Port Blair', airportName: 'Veer Savarkar International Airport', country: 'India', iata: 'IXZ', region: 'Asia' },
  { city: 'Karachi', airportName: 'Jinnah International Airport', country: 'Pakistan', iata: 'KHI', region: 'Asia' },
  { city: 'Lahore', airportName: 'Allama Iqbal International Airport', country: 'Pakistan', iata: 'LHE', region: 'Asia' },
  { city: 'Islamabad', airportName: 'Islamabad International Airport', country: 'Pakistan', iata: 'ISB', region: 'Asia' },
  { city: 'Peshawar', airportName: 'Bacha Khan International Airport', country: 'Pakistan', iata: 'PEW', region: 'Asia' },
  { city: 'Sialkot', airportName: 'Sialkot International Airport', country: 'Pakistan', iata: 'SKT', region: 'Asia' },
  { city: 'Quetta', airportName: 'Quetta International Airport', country: 'Pakistan', iata: 'UET', region: 'Asia' },
  { city: 'Faisalabad', airportName: 'Faisalabad International Airport', country: 'Pakistan', iata: 'LYP', region: 'Asia' },
  { city: 'Multan', airportName: 'Multan International Airport', country: 'Pakistan', iata: 'MUX', region: 'Asia' },
  { city: 'Rahim Yar Khan', airportName: 'Shaikh Zayed International Airport', country: 'Pakistan', iata: 'RYK', region: 'Asia' },
  { city: 'Colombo', airportName: 'Bandaranaike International Airport', country: 'Sri Lanka', iata: 'CMB', region: 'Asia' },
  { city: 'Hambantota', airportName: 'Mattala Rajapaksa International Airport', country: 'Sri Lanka', iata: 'HRI', region: 'Asia' },
  { city: 'Jaffna', airportName: 'Jaffna International Airport', country: 'Sri Lanka', iata: 'JAF', region: 'Asia' },
  { city: 'Male', airportName: 'Velana International Airport', country: 'Maldives', iata: 'MLE', region: 'Asia' },
  { city: 'Gan Island', airportName: 'Gan International Airport', country: 'Maldives', iata: 'GAN', region: 'Asia' },
  { city: 'Dharavandhoo', airportName: 'Dharavandhoo Airport', country: 'Maldives', iata: 'DRV', region: 'Asia' },
  { city: 'Kathmandu', airportName: 'Tribhuvan International Airport', country: 'Nepal', iata: 'KTM', region: 'Asia' },
  { city: 'Pokhara', airportName: 'Pokhara International Airport', country: 'Nepal', iata: 'PKR', region: 'Asia' },
  { city: 'Bhairahawa', airportName: 'Gautam Buddha International Airport', country: 'Nepal', iata: 'BWA', region: 'Asia' },
  { city: 'Paro', airportName: 'Paro Airport', country: 'Bhutan', iata: 'PBH', region: 'Asia' },
  { city: 'Kabul', airportName: 'Kabul International Airport', country: 'Afghanistan', iata: 'KBL', region: 'Asia' },
  { city: 'Kandahar', airportName: 'Ahmad Shah Baba International Airport', country: 'Afghanistan', iata: 'KDH', region: 'Asia' },
  { city: 'Herat', airportName: 'Herat International Airport', country: 'Afghanistan', iata: 'HEA', region: 'Asia' },
  { city: 'Mazar-i-Sharif', airportName: 'Mazar-i-Sharif International Airport', country: 'Afghanistan', iata: 'MZR', region: 'Asia' },
  { city: 'Bangkok', airportName: 'Suvarnabhumi Airport', country: 'Thailand', iata: 'BKK', region: 'Asia' },
  { city: 'Bangkok', airportName: 'Don Mueang International Airport', country: 'Thailand', iata: 'DMK', region: 'Asia' },
  { city: 'Phuket', airportName: 'Phuket International Airport', country: 'Thailand', iata: 'HKT', region: 'Asia' },
  { city: 'Chiang Mai', airportName: 'Chiang Mai International Airport', country: 'Thailand', iata: 'CNX', region: 'Asia' },
  { city: 'Krabi', airportName: 'Krabi International Airport', country: 'Thailand', iata: 'KBV', region: 'Asia' },
  { city: 'Koh Samui', airportName: 'Samui International Airport', country: 'Thailand', iata: 'USM', region: 'Asia' },
  { city: 'Hat Yai', airportName: 'Hat Yai International Airport', country: 'Thailand', iata: 'HDY', region: 'Asia' },
  { city: 'Chiang Rai', airportName: 'Mae Fah Luang Chiang Rai International Airport', country: 'Thailand', iata: 'CEI', region: 'Asia' },
  { city: 'Kuala Lumpur', airportName: 'Kuala Lumpur International Airport', country: 'Malaysia', iata: 'KUL', region: 'Asia' },
  { city: 'Kuala Lumpur', airportName: 'Sultan Abdul Aziz Shah Airport', country: 'Malaysia', iata: 'SZB', region: 'Asia' },
  { city: 'Penang', airportName: 'Penang International Airport', country: 'Malaysia', iata: 'PEN', region: 'Asia' },
  { city: 'Johor Bahru', airportName: 'Senai International Airport', country: 'Malaysia', iata: 'JHB', region: 'Asia' },
  { city: 'Kota Kinabalu', airportName: 'Kota Kinabalu International Airport', country: 'Malaysia', iata: 'BKI', region: 'Asia' },
  { city: 'Kuching', airportName: 'Kuching International Airport', country: 'Malaysia', iata: 'KCH', region: 'Asia' },
  { city: 'Langkawi', airportName: 'Langkawi International Airport', country: 'Malaysia', iata: 'LGK', region: 'Asia' },
  { city: 'Singapore', airportName: 'Changi Airport', country: 'Singapore', iata: 'SIN', region: 'Asia' },
  { city: 'Jakarta', airportName: 'Soekarno-Hatta International Airport', country: 'Indonesia', iata: 'CGK', region: 'Asia' },
  { city: 'Bali', airportName: 'Ngurah Rai International Airport', country: 'Indonesia', iata: 'DPS', region: 'Asia' },
  { city: 'Surabaya', airportName: 'Juanda International Airport', country: 'Indonesia', iata: 'SUB', region: 'Asia' },
  { city: 'Makassar', airportName: 'Sultan Hasanuddin International Airport', country: 'Indonesia', iata: 'UPG', region: 'Asia' },
  { city: 'Medan', airportName: 'Kualanamu International Airport', country: 'Indonesia', iata: 'KNO', region: 'Asia' },
  { city: 'Yogyakarta', airportName: 'Yogyakarta International Airport', country: 'Indonesia', iata: 'YIA', region: 'Asia' },
  { city: 'Bandung', airportName: 'Husein Sastranegara International Airport', country: 'Indonesia', iata: 'BDO', region: 'Asia' },
  { city: 'Lombok', airportName: 'Lombok International Airport', country: 'Indonesia', iata: 'LOP', region: 'Asia' },
  { city: 'Manila', airportName: 'Ninoy Aquino International Airport', country: 'Philippines', iata: 'MNL', region: 'Asia' },
  { city: 'Cebu', airportName: 'Mactan-Cebu International Airport', country: 'Philippines', iata: 'CEB', region: 'Asia' },
  { city: 'Davao', airportName: 'Francisco Bangoy International Airport', country: 'Philippines', iata: 'DVO', region: 'Asia' },
  { city: 'Clark', airportName: 'Clark International Airport', country: 'Philippines', iata: 'CRK', region: 'Asia' },
  { city: 'Iloilo', airportName: 'Iloilo International Airport', country: 'Philippines', iata: 'ILO', region: 'Asia' },
  { city: 'Ho Chi Minh City', airportName: 'Tan Son Nhat International Airport', country: 'Vietnam', iata: 'SGN', region: 'Asia' },
  { city: 'Hanoi', airportName: 'Noi Bai International Airport', country: 'Vietnam', iata: 'HAN', region: 'Asia' },
  { city: 'Da Nang', airportName: 'Da Nang International Airport', country: 'Vietnam', iata: 'DAD', region: 'Asia' },
  { city: 'Nha Trang', airportName: 'Cam Ranh International Airport', country: 'Vietnam', iata: 'CXR', region: 'Asia' },
  { city: 'Phu Quoc', airportName: 'Phu Quoc International Airport', country: 'Vietnam', iata: 'PQC', region: 'Asia' },
  { city: 'Phnom Penh', airportName: 'Phnom Penh International Airport', country: 'Cambodia', iata: 'PNH', region: 'Asia' },
  { city: 'Siem Reap', airportName: 'Siem Reap-Angkor International Airport', country: 'Cambodia', iata: 'SAI', region: 'Asia' },
  { city: 'Sihanoukville', airportName: 'Sihanouk International Airport', country: 'Cambodia', iata: 'KOS', region: 'Asia' },
  { city: 'Vientiane', airportName: 'Wattay International Airport', country: 'Laos', iata: 'VTE', region: 'Asia' },
  { city: 'Luang Prabang', airportName: 'Luang Prabang International Airport', country: 'Laos', iata: 'LPQ', region: 'Asia' },
  { city: 'Bandar Seri Begawan', airportName: 'Brunei International Airport', country: 'Brunei', iata: 'BWN', region: 'Asia' },
  { city: 'Yangon', airportName: 'Yangon International Airport', country: 'Myanmar', iata: 'RGN', region: 'Asia' },
  { city: 'Mandalay', airportName: 'Mandalay International Airport', country: 'Myanmar', iata: 'MDL', region: 'Asia' },
  { city: 'Naypyidaw', airportName: 'Naypyidaw International Airport', country: 'Myanmar', iata: 'NYT', region: 'Asia' },
  { city: 'Beijing', airportName: 'Beijing Capital International Airport', country: 'China', iata: 'PEK', region: 'Asia' },
  { city: 'Beijing', airportName: 'Beijing Daxing International Airport', country: 'China', iata: 'PKX', region: 'Asia' },
  { city: 'Shanghai', airportName: 'Shanghai Pudong International Airport', country: 'China', iata: 'PVG', region: 'Asia' },
  { city: 'Shanghai', airportName: 'Shanghai Hongqiao International Airport', country: 'China', iata: 'SHA', region: 'Asia' },
  { city: 'Guangzhou', airportName: 'Guangzhou Baiyun International Airport', country: 'China', iata: 'CAN', region: 'Asia' },
  { city: 'Shenzhen', airportName: 'Shenzhen Baoan International Airport', country: 'China', iata: 'SZX', region: 'Asia' },
  { city: 'Chengdu', airportName: 'Chengdu Tianfu International Airport', country: 'China', iata: 'TFU', region: 'Asia' },
  { city: 'Chongqing', airportName: 'Chongqing Jiangbei International Airport', country: 'China', iata: 'CKG', region: 'Asia' },
  { city: 'Xian', airportName: 'Xian Xianyang International Airport', country: 'China', iata: 'XIY', region: 'Asia' },
  { city: 'Kunming', airportName: 'Kunming Changshui International Airport', country: 'China', iata: 'KMG', region: 'Asia' },
  { city: 'Hangzhou', airportName: 'Hangzhou Xiaoshan International Airport', country: 'China', iata: 'HGH', region: 'Asia' },
  { city: 'Nanjing', airportName: 'Nanjing Lukou International Airport', country: 'China', iata: 'NKG', region: 'Asia' },
  { city: 'Xiamen', airportName: 'Xiamen Gaoqi International Airport', country: 'China', iata: 'XMN', region: 'Asia' },
  { city: 'Qingdao', airportName: 'Qingdao Jiaodong International Airport', country: 'China', iata: 'TAO', region: 'Asia' },
  { city: 'Wuhan', airportName: 'Wuhan Tianhe International Airport', country: 'China', iata: 'WUH', region: 'Asia' },
  { city: 'Hong Kong', airportName: 'Hong Kong International Airport', country: 'Hong Kong', iata: 'HKG', region: 'Asia' },
  { city: 'Macau', airportName: 'Macau International Airport', country: 'Macau', iata: 'MFM', region: 'Asia' },
  { city: 'Taipei', airportName: 'Taiwan Taoyuan International Airport', country: 'Taiwan', iata: 'TPE', region: 'Asia' },
  { city: 'Taipei', airportName: 'Taipei Songshan Airport', country: 'Taiwan', iata: 'TSA', region: 'Asia' },
  { city: 'Kaohsiung', airportName: 'Kaohsiung International Airport', country: 'Taiwan', iata: 'KHH', region: 'Asia' },
  { city: 'Tokyo', airportName: 'Tokyo Haneda Airport', country: 'Japan', iata: 'HND', region: 'Asia' },
  { city: 'Tokyo', airportName: 'Narita International Airport', country: 'Japan', iata: 'NRT', region: 'Asia' },
  { city: 'Osaka', airportName: 'Kansai International Airport', country: 'Japan', iata: 'KIX', region: 'Asia' },
  { city: 'Nagoya', airportName: 'Chubu Centrair International Airport', country: 'Japan', iata: 'NGO', region: 'Asia' },
  { city: 'Fukuoka', airportName: 'Fukuoka Airport', country: 'Japan', iata: 'FUK', region: 'Asia' },
  { city: 'Sapporo', airportName: 'New Chitose Airport', country: 'Japan', iata: 'CTS', region: 'Asia' },
  { city: 'Okinawa', airportName: 'Naha Airport', country: 'Japan', iata: 'OKA', region: 'Asia' },
  { city: 'Seoul', airportName: 'Incheon International Airport', country: 'South Korea', iata: 'ICN', region: 'Asia' },
  { city: 'Seoul', airportName: 'Gimpo International Airport', country: 'South Korea', iata: 'GMP', region: 'Asia' },
  { city: 'Busan', airportName: 'Gimhae International Airport', country: 'South Korea', iata: 'PUS', region: 'Asia' },
  { city: 'Jeju', airportName: 'Jeju International Airport', country: 'South Korea', iata: 'CJU', region: 'Asia' },
  { city: 'Ulaanbaatar', airportName: 'Chinggis Khaan International Airport', country: 'Mongolia', iata: 'UBN', region: 'Asia' },
  { city: 'Almaty', airportName: 'Almaty International Airport', country: 'Kazakhstan', iata: 'ALA', region: 'Asia' },
  { city: 'Astana', airportName: 'Nursultan Nazarbayev International Airport', country: 'Kazakhstan', iata: 'NQZ', region: 'Asia' },
  { city: 'Shymkent', airportName: 'Shymkent International Airport', country: 'Kazakhstan', iata: 'CIT', region: 'Asia' },
  { city: 'Tashkent', airportName: 'Islam Karimov Tashkent International Airport', country: 'Uzbekistan', iata: 'TAS', region: 'Asia' },
  { city: 'Samarkand', airportName: 'Samarkand International Airport', country: 'Uzbekistan', iata: 'SKD', region: 'Asia' },
  { city: 'Bukhara', airportName: 'Bukhara International Airport', country: 'Uzbekistan', iata: 'BHK', region: 'Asia' },
  { city: 'Bishkek', airportName: 'Manas International Airport', country: 'Kyrgyzstan', iata: 'FRU', region: 'Asia' },
  { city: 'Osh', airportName: 'Osh Airport', country: 'Kyrgyzstan', iata: 'OSS', region: 'Asia' },
  { city: 'Dushanbe', airportName: 'Dushanbe International Airport', country: 'Tajikistan', iata: 'DYU', region: 'Asia' },
  { city: 'Ashgabat', airportName: 'Ashgabat International Airport', country: 'Turkmenistan', iata: 'ASB', region: 'Asia' },

  { city: 'Cairo', airportName: 'Cairo International Airport', country: 'Egypt', iata: 'CAI', region: 'Africa' },
  { city: 'Giza', airportName: 'Sphinx International Airport', country: 'Egypt', iata: 'SPX', region: 'Africa' },
  { city: 'Hurghada', airportName: 'Hurghada International Airport', country: 'Egypt', iata: 'HRG', region: 'Africa' },
  { city: 'Sharm El Sheikh', airportName: 'Sharm El Sheikh International Airport', country: 'Egypt', iata: 'SSH', region: 'Africa' },
  { city: 'Luxor', airportName: 'Luxor International Airport', country: 'Egypt', iata: 'LXR', region: 'Africa' },
  { city: 'Alexandria', airportName: 'Borg El Arab Airport', country: 'Egypt', iata: 'HBE', region: 'Africa' },
  { city: 'Casablanca', airportName: 'Mohammed V International Airport', country: 'Morocco', iata: 'CMN', region: 'Africa' },
  { city: 'Marrakesh', airportName: 'Marrakesh Menara Airport', country: 'Morocco', iata: 'RAK', region: 'Africa' },
  { city: 'Agadir', airportName: 'Agadir Al Massira Airport', country: 'Morocco', iata: 'AGA', region: 'Africa' },
  { city: 'Tangier', airportName: 'Tangier Ibn Battouta Airport', country: 'Morocco', iata: 'TNG', region: 'Africa' },
  { city: 'Fez', airportName: 'Fes-Saiss Airport', country: 'Morocco', iata: 'FEZ', region: 'Africa' },
  { city: 'Rabat', airportName: 'Rabat-Sale Airport', country: 'Morocco', iata: 'RBA', region: 'Africa' },
  { city: 'Algiers', airportName: 'Houari Boumediene Airport', country: 'Algeria', iata: 'ALG', region: 'Africa' },
  { city: 'Oran', airportName: 'Ahmed Ben Bella Airport', country: 'Algeria', iata: 'ORN', region: 'Africa' },
  { city: 'Constantine', airportName: 'Mohamed Boudiaf International Airport', country: 'Algeria', iata: 'CZL', region: 'Africa' },
  { city: 'Annaba', airportName: 'Rabah Bitat Airport', country: 'Algeria', iata: 'AAE', region: 'Africa' },
  { city: 'Tlemcen', airportName: 'Zenata Airport', country: 'Algeria', iata: 'TLM', region: 'Africa' },
  { city: 'Tunis', airportName: 'Tunis-Carthage International Airport', country: 'Tunisia', iata: 'TUN', region: 'Africa' },
  { city: 'Djerba', airportName: 'Djerba-Zarzis International Airport', country: 'Tunisia', iata: 'DJE', region: 'Africa' },
  { city: 'Monastir', airportName: 'Monastir Habib Bourguiba International Airport', country: 'Tunisia', iata: 'MIR', region: 'Africa' },
  { city: 'Tripoli', airportName: 'Tripoli International Airport', country: 'Libya', iata: 'TIP', region: 'Africa' },
  { city: 'Benghazi', airportName: 'Benina International Airport', country: 'Libya', iata: 'BEN', region: 'Africa' },
  { city: 'Khartoum', airportName: 'Khartoum International Airport', country: 'Sudan', iata: 'KRT', region: 'Africa' },
  { city: 'Port Sudan', airportName: 'Port Sudan New International Airport', country: 'Sudan', iata: 'PZU', region: 'Africa' },
  { city: 'Addis Ababa', airportName: 'Bole International Airport', country: 'Ethiopia', iata: 'ADD', region: 'Africa' },
  { city: 'Dire Dawa', airportName: 'Aba Tenna Dejazmach Yilma International Airport', country: 'Ethiopia', iata: 'DIR', region: 'Africa' },
  { city: 'Bahir Dar', airportName: 'Bahir Dar Airport', country: 'Ethiopia', iata: 'BJR', region: 'Africa' },
  { city: 'Gondar', airportName: 'Gondar Airport', country: 'Ethiopia', iata: 'GDQ', region: 'Africa' },
  { city: 'Nairobi', airportName: 'Jomo Kenyatta International Airport', country: 'Kenya', iata: 'NBO', region: 'Africa' },
  { city: 'Mombasa', airportName: 'Moi International Airport', country: 'Kenya', iata: 'MBA', region: 'Africa' },
  { city: 'Kisumu', airportName: 'Kisumu International Airport', country: 'Kenya', iata: 'KIS', region: 'Africa' },
  { city: 'Eldoret', airportName: 'Eldoret International Airport', country: 'Kenya', iata: 'EDL', region: 'Africa' },
  { city: 'Dar es Salaam', airportName: 'Julius Nyerere International Airport', country: 'Tanzania', iata: 'DAR', region: 'Africa' },
  { city: 'Kilimanjaro', airportName: 'Kilimanjaro International Airport', country: 'Tanzania', iata: 'JRO', region: 'Africa' },
  { city: 'Zanzibar', airportName: 'Abeid Amani Karume International Airport', country: 'Tanzania', iata: 'ZNZ', region: 'Africa' },
  { city: 'Mwanza', airportName: 'Mwanza Airport', country: 'Tanzania', iata: 'MWZ', region: 'Africa' },
  { city: 'Entebbe', airportName: 'Entebbe International Airport', country: 'Uganda', iata: 'EBB', region: 'Africa' },
  { city: 'Kigali', airportName: 'Kigali International Airport', country: 'Rwanda', iata: 'KGL', region: 'Africa' },
  { city: 'Bujumbura', airportName: 'Melchior Ndadaye International Airport', country: 'Burundi', iata: 'BJM', region: 'Africa' },
  { city: 'Kinshasa', airportName: 'N Djili International Airport', country: 'Democratic Republic of the Congo', iata: 'FIH', region: 'Africa' },
  { city: 'Lubumbashi', airportName: 'Lubumbashi International Airport', country: 'Democratic Republic of the Congo', iata: 'FBM', region: 'Africa' },
  { city: 'Goma', airportName: 'Goma International Airport', country: 'Democratic Republic of the Congo', iata: 'GOM', region: 'Africa' },
  { city: 'Brazzaville', airportName: 'Maya-Maya Airport', country: 'Republic of the Congo', iata: 'BZV', region: 'Africa' },
  { city: 'Pointe-Noire', airportName: 'Antonio Agostinho Neto International Airport', country: 'Republic of the Congo', iata: 'PNR', region: 'Africa' },
  { city: 'Luanda', airportName: 'Quatro de Fevereiro Airport', country: 'Angola', iata: 'LAD', region: 'Africa' },
  { city: 'Lubango', airportName: 'Mukanka Airport', country: 'Angola', iata: 'SDD', region: 'Africa' },
  { city: 'Lagos', airportName: 'Murtala Muhammed International Airport', country: 'Nigeria', iata: 'LOS', region: 'Africa' },
  { city: 'Abuja', airportName: 'Nnamdi Azikiwe International Airport', country: 'Nigeria', iata: 'ABV', region: 'Africa' },
  { city: 'Kano', airportName: 'Mallam Aminu Kano International Airport', country: 'Nigeria', iata: 'KAN', region: 'Africa' },
  { city: 'Port Harcourt', airportName: 'Port Harcourt International Airport', country: 'Nigeria', iata: 'PHC', region: 'Africa' },
  { city: 'Enugu', airportName: 'Akanu Ibiam International Airport', country: 'Nigeria', iata: 'ENU', region: 'Africa' },
  { city: 'Accra', airportName: 'Kotoka International Airport', country: 'Ghana', iata: 'ACC', region: 'Africa' },
  { city: 'Kumasi', airportName: 'Kumasi Airport', country: 'Ghana', iata: 'KMS', region: 'Africa' },
  { city: 'Takoradi', airportName: 'Takoradi Airport', country: 'Ghana', iata: 'TKD', region: 'Africa' },
  { city: 'Dakar', airportName: 'Blaise Diagne International Airport', country: 'Senegal', iata: 'DSS', region: 'Africa' },
  { city: 'Abidjan', airportName: 'Felix Houphouet Boigny International Airport', country: 'Cote d Ivoire', iata: 'ABJ', region: 'Africa' },
  { city: 'Douala', airportName: 'Douala International Airport', country: 'Cameroon', iata: 'DLA', region: 'Africa' },
  { city: 'Yaounde', airportName: 'Yaounde Nsimalen International Airport', country: 'Cameroon', iata: 'NSI', region: 'Africa' },
  { city: 'Johannesburg', airportName: 'O. R. Tambo International Airport', country: 'South Africa', iata: 'JNB', region: 'Africa' },
  { city: 'Cape Town', airportName: 'Cape Town International Airport', country: 'South Africa', iata: 'CPT', region: 'Africa' },
  { city: 'Durban', airportName: 'King Shaka International Airport', country: 'South Africa', iata: 'DUR', region: 'Africa' },
  { city: 'Gqeberha', airportName: 'Chief Dawid Stuurman International Airport', country: 'South Africa', iata: 'PLZ', region: 'Africa' },
  { city: 'East London', airportName: 'East London Airport', country: 'South Africa', iata: 'ELS', region: 'Africa' },
  { city: 'Mbombela', airportName: 'Kruger Mpumalanga International Airport', country: 'South Africa', iata: 'MQP', region: 'Africa' },
  { city: 'Harare', airportName: 'Robert Gabriel Mugabe International Airport', country: 'Zimbabwe', iata: 'HRE', region: 'Africa' },
  { city: 'Victoria Falls', airportName: 'Victoria Falls Airport', country: 'Zimbabwe', iata: 'VFA', region: 'Africa' },
  { city: 'Bulawayo', airportName: 'Joshua Mqabuko Nkomo International Airport', country: 'Zimbabwe', iata: 'BUQ', region: 'Africa' },
  { city: 'Lusaka', airportName: 'Kenneth Kaunda International Airport', country: 'Zambia', iata: 'LUN', region: 'Africa' },
  { city: 'Ndola', airportName: 'Simon Mwansa Kapwepwe International Airport', country: 'Zambia', iata: 'NLA', region: 'Africa' },
  { city: 'Livingstone', airportName: 'Harry Mwanga Nkumbula International Airport', country: 'Zambia', iata: 'LVI', region: 'Africa' },
  { city: 'Windhoek', airportName: 'Hosea Kutako International Airport', country: 'Namibia', iata: 'WDH', region: 'Africa' },
  { city: 'Walvis Bay', airportName: 'Walvis Bay Airport', country: 'Namibia', iata: 'WVB', region: 'Africa' },
  { city: 'Gaborone', airportName: 'Sir Seretse Khama International Airport', country: 'Botswana', iata: 'GBE', region: 'Africa' },
  { city: 'Maun', airportName: 'Maun Airport', country: 'Botswana', iata: 'MUB', region: 'Africa' },
  { city: 'Maputo', airportName: 'Maputo International Airport', country: 'Mozambique', iata: 'MPM', region: 'Africa' },
  { city: 'Beira', airportName: 'Beira Airport', country: 'Mozambique', iata: 'BEW', region: 'Africa' },
  { city: 'Antananarivo', airportName: 'Ivato International Airport', country: 'Madagascar', iata: 'TNR', region: 'Africa' },
  { city: 'Nosy Be', airportName: 'Fascene Airport', country: 'Madagascar', iata: 'NOS', region: 'Africa' },
  { city: 'Mauritius', airportName: 'Sir Seewoosagur Ramgoolam International Airport', country: 'Mauritius', iata: 'MRU', region: 'Africa' },
  { city: 'Rodrigues', airportName: 'Sir Gaetan Duval Airport', country: 'Mauritius', iata: 'RRG', region: 'Africa' },
  { city: 'Mahe', airportName: 'Seychelles International Airport', country: 'Seychelles', iata: 'SEZ', region: 'Africa' },
  { city: 'Praia', airportName: 'Nelson Mandela International Airport', country: 'Cape Verde', iata: 'RAI', region: 'Africa' },
  { city: 'Sal', airportName: 'Amilcar Cabral International Airport', country: 'Cape Verde', iata: 'SID', region: 'Africa' },
  { city: 'Bamako', airportName: 'Modibo Keita International Airport', country: 'Mali', iata: 'BKO', region: 'Africa' },
  { city: 'Ouagadougou', airportName: 'Ouagadougou Airport', country: 'Burkina Faso', iata: 'OUA', region: 'Africa' },
  { city: 'Niamey', airportName: 'Diori Hamani International Airport', country: 'Niger', iata: 'NIM', region: 'Africa' },
  { city: 'Cotonou', airportName: 'Cadjehoun Airport', country: 'Benin', iata: 'COO', region: 'Africa' },
  { city: 'Lome', airportName: 'Lome-Tokoin International Airport', country: 'Togo', iata: 'LFW', region: 'Africa' },
  { city: 'Monrovia', airportName: 'Roberts International Airport', country: 'Liberia', iata: 'ROB', region: 'Africa' },
  { city: 'Freetown', airportName: 'Freetown International Airport', country: 'Sierra Leone', iata: 'FNA', region: 'Africa' },
  { city: 'Banjul', airportName: 'Banjul International Airport', country: 'Gambia', iata: 'BJL', region: 'Africa' },
  { city: 'Conakry', airportName: 'Ahmed Sekou Toure International Airport', country: 'Guinea', iata: 'CKY', region: 'Africa' },
  { city: 'Libreville', airportName: 'Leon-Mba International Airport', country: 'Gabon', iata: 'LBV', region: 'Africa' },
  { city: 'Port Gentil', airportName: 'Port-Gentil International Airport', country: 'Gabon', iata: 'POG', region: 'Africa' },
  { city: 'Malabo', airportName: 'Malabo International Airport', country: 'Equatorial Guinea', iata: 'SSG', region: 'Africa' },
  { city: 'Sao Tome', airportName: 'Sao Tome International Airport', country: 'Sao Tome and Principe', iata: 'TMS', region: 'Africa' },
  { city: 'Lilongwe', airportName: 'Kamuzu International Airport', country: 'Malawi', iata: 'LLW', region: 'Africa' },
  { city: 'Blantyre', airportName: 'Chileka International Airport', country: 'Malawi', iata: 'BLZ', region: 'Africa' },
  { city: 'Maseru', airportName: 'Moshoeshoe I International Airport', country: 'Lesotho', iata: 'MSU', region: 'Africa' },
  { city: 'Manzini', airportName: 'King Mswati III International Airport', country: 'Eswatini', iata: 'SHO', region: 'Africa' },
  { city: 'Moroni', airportName: 'Prince Said Ibrahim International Airport', country: 'Comoros', iata: 'HAH', region: 'Africa' },
  { city: 'Djibouti', airportName: 'Djibouti-Ambouli International Airport', country: 'Djibouti', iata: 'JIB', region: 'Africa' },
  { city: 'Asmara', airportName: 'Asmara International Airport', country: 'Eritrea', iata: 'ASM', region: 'Africa' },
  { city: 'Mogadishu', airportName: 'Aden Adde International Airport', country: 'Somalia', iata: 'MGQ', region: 'Africa' },
  { city: 'Hargeisa', airportName: 'Hargeisa Egal International Airport', country: 'Somalia', iata: 'HGA', region: 'Africa' },
];

export function formatAirportRouteLabel(airport: AirportOption): string {
  return `${airport.city} - ${airport.airportName} [${airport.iata}] - ${airport.country}`;
}

export const AIRPORT_ROUTE_OPTIONS = AIRPORT_PRESETS.map(formatAirportRouteLabel);
export const AIRPORT_ROUTE_OPTION_COUNT = AIRPORT_ROUTE_OPTIONS.length;

export const UAE_ORIGIN_OPTIONS = AIRPORT_PRESETS
  .filter((airport) => airport.country === 'United Arab Emirates')
  .map(formatAirportRouteLabel);

export function getAirportRouteLabelByIata(iataCode: string): string | undefined {
  const normalized = iataCode.trim().toUpperCase();
  const airport = AIRPORT_PRESETS.find((item) => item.iata === normalized);
  return airport ? formatAirportRouteLabel(airport) : undefined;
}

export function buildCustomAirportRouteLabel(airportName: string, iataCode: string): string {
  const name = airportName.trim().replace(/\s+/g, ' ');
  const iata = iataCode.trim().toUpperCase().replace(/[^A-Z]/g, '').slice(0, 3);

  if (!name && !iata) return '';
  if (!iata) return name;
  if (!name) return `[${iata}]`;
  return `${name} [${iata}]`;
}
